org.slf4j.simpleLogger.defaultLogLevel=INFO

org.slf4j.simpleLogger.log.org.bitcoinj.core.PeerGroup=WARN
org.slf4j.simpleLogger.log.org.bitcoinj.core.Peer=WARN

org.slf4j.simpleLogger.log.org.bitcoinj.net.NioClientManager=WARN
org.slf4j.simpleLogger.log.org.bitcoinj.net.ConnectionHandler=ERROR
org.slf4j.simpleLogger.log.org.bitcoinj.core.PeerSocketHandler=WARN
